[package]
name = "rplidar"
description = "Driver for Slamtec RPLIDAR series laser sensors"
version = "0.9.0"
keywords = ["Slamtec", "Rplidar", "Driver"]
edition = "2021"

[lib]
name = "rplidar"
path = "src/lib.rs"

[dependencies]
byteorder = "1.2"
crc32fast = "1.4"
log = "0.4"


